export const MEMES = [
    { src: "/images/meme2.png" },
    { src: "/images/meme10.jpg" },
    { src: "/images/meme4.jpg" },
    { src: "/images/meme14.jpg" },
    { src: "/images/meme5.jpg" },
    { src: "/images/meme6.jpg" },
    { src: "/images/meme1.jpg" },
    { src: "/images/meme18.jpg" },
    { src: "/images/meme8.jpg" },
    { src: "/images/meme15.jpg" },
    { src: "/images/meme11.jpg" },
    { src: "/images/meme9.jpg" },
    { src: "/images/meme16.jpg" },
    { src: "/images/meme12.jpg" },
    { src: "/images/meme7.jpg" },
    { src: "/images/meme13.jpg" },
    { src: "/images/meme3.jpg" },
    { src: "/images/meme17.jpg" },
    { src: "/images/meme19.jpg" },
];